name: Main Branch Push Notification
run-name: Alert raised on ${{ github.ref }} by ${{ github.actor }}
# TODO: implement some safeguards to guide students and signal lead that someone may need help. /
# Will determine events to trigger as we see the most common errors
on:
  push:
    branches:
      - main

jobs:
  notify-leaders:
    runs-on: ubuntu-latest

    steps:
      - name: Get Pusher's Username
        id: pusher
        run: echo "::set-output name=username::${{ github.actor }}"

      - name: Send Notification to Admins
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # does not need defined. This is available in every repository.
          # "bcko", "brandondombrowsky",
          script: |
            # Specify the usernames of the admins
            const admins = ["theGaryLarson"];        
            const pusher = "${{ steps.pusher.outputs.username }}";
            const message = `@${pusher} attempted to push directly to the main branch without a pull request. Remind how to submit a pull request instead.`;

            admins.forEach((admin) => {
              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: message,
              });
            });

            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `You attempted to push directly to the main branch without a pull request. Please submit a pull request instead.`,
            });
