name: Continuous Integration
on:
  workflow_call: # required when creating a reusable workflow
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # was originally using v14 but getting error. I believe using v2 would allow older version

      - name: Install dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint --if-present

# TODO: Tests
#      - name: Run Unit Tests
#        run: npm run test:unit
#
#      - name: Run Integration Tests
#        run: npm run test:integration
#
#      - name: Run Component Tests
#        run: npm run test:components
#
#      - name: Run API Tests
#        run: npm run test:api
#
#      - name: Run End-to-End Tests
#        run: npm run test:e2e
#
##      - name: Run Snapshot Tests
##        run: npm run test:snapshot
#
#      - name: Run Routing Tests
#        run: npm run test:routing
#
#      - name: Run Redux/State Management Tests
#        run: npm run test:redux
#
#      - name: Run Error Handling Tests
#        run: npm run test:error-handling


