name: Continuous Integration
on:
  workflow_call: # required when creating a reusable workflow
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # was originally using v14 but getting error. I believe using v2 would allow older version

      - name: Install dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint --if-present

# TODO: Tests
#      - name: Run tests
#        run: npm test


