name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:


  Continuous-Integration:
    uses: ./.github/workflows/ci.yml
    if_merged:
      if: github.event.pull_request.merged == true || github.event_name == 'push'

  Continuous-Deployment:
    uses: ./.github/workflows/cd.yml
    if_merged:
      if: github.event.pull_request.merged == true || github.event_name == 'push'



