name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true || github.event_name == 'push'

  Continuous-Integration:
    uses: ./.github/workflows/ci.yml

  Continuous-Deployment:
    uses: ./.github/workflows/cd.yml



